name: FinTrust API Automation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      # 🔹 Install backend dependencies
      - name: Install backend dependencies
        run: |
          pip install flask flask_sqlalchemy flask_jwt_extended

      # 🔹 Start backend server
      - name: Start backend
        run: |
          python app.py &
          sleep 5

      # 🔹 Run tests
      - name: Run tests
        env:
          BASE_URL: http://127.0.0.1:5000
        run: |
          pytest --html=report.html --self-contained-html